[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seatrades"
version = "2024.0.0"
dependencies = [
  "pandera",
  "pandas",
  "pulp",
  "altair",
]
requires-python = ">=3.8"
authors = [
  {name = "Gavin Grochowski", email = "grochowskigavin@gmail.com"},
]
maintainers = [
  {name = "Gavin Grochowski", email = "grochowskigavin@gmail.com"}
]
description = "A tool to help Keats Camps using math."
readme = "README.md"
license = {file = "LICENSE.txt"}

[project.urls]
Repository = "https://github.com/gavingro/seatrades"

[tools.setuptools]
packages = ["seatrades"]

[tool.pytest.ini_options]
testpaths = "tests"
addopts = "-v -ra --cov src"
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
